# Generated by Django 4.1 on 2023-08-16 10:43

from django.db import migrations, models
import industry.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryWithoutGis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.CharField(blank=True, max_length=10, null=True, validators=[industry.validators.nepali_date_validator])),
                ('industry_reg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_name', models.CharField(blank=True, max_length=150, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_address', models.CharField(blank=True, max_length=100, null=True)),
                ('fixed_capital', models.FloatField(blank=True, default=0, null=True)),
                ('current_capital', models.FloatField(blank=True, default=0, null=True)),
                ('total_capital', models.FloatField(blank=True, default=0, null=True)),
                ('yearly_capacity', models.FloatField(blank=True, default=0, null=True)),
                ('male', models.IntegerField(blank=True, default=0, null=True)),
                ('female', models.IntegerField(blank=True, default=0, null=True)),
                ('total_manpower', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
