# Generated by Django 4.1 on 2023-08-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_without_gis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industrywithoutgis',
            old_name='industry_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='caste',
            field=models.CharField(blank=True, choices=[('DALIT', 'दलित (Dalit)'), ('JANAJATI', 'जनजाती (Janajati)'), ('OTHERS', 'अन्य (Others)')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='current_running_capacity',
            field=models.CharField(blank=True, choices=[('A', '७०-१००% (70-100%)'), ('B', '५०-७०% (50-70%)'), ('C', '५०% भन्दा कम (Less than 50%)'), ('D', '२५% भन्दा कम (Less than 25%)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='current_status',
            field=models.CharField(blank=True, choices=[('A', 'चालु(Active)'), ('I', 'निष्कृय(Inactive)')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='district',
            field=models.CharField(blank=True, choices=[('KAILALI', 'कैलाली'), ('KANCHANPUR', 'कञ्चनपुर'), ('DADELDHURA', 'डडेल्धुरा'), ('DOTI', 'डोटी'), ('ACHHAM', 'अछाम'), ('BAJURA', 'बाजुरा'), ('BAJHANG', 'बझाङ'), ('BAITADI', 'बैतडी'), ('DARCHULA', 'दार्चुला')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='foreign',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='indigenous',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='industry_acc_product',
            field=models.CharField(blank=True, choices=[('E', 'उर्जामूलक (Energy)'), ('MF', 'उत्पादनमूलक (Manufacturing)'), ('AF', 'कृषि तथा वन पैदावारमा आधारित (Agricultural or Forestry based)'), ('MI', 'खनिज(Mineral)'), ('I', 'पूर्वाधार(Infrastructure)'), ('T', 'पर्यटन(Tourism)'), ('IC', 'सूचना तथा संचार प्रविधि(Information and Communication)'), ('S', 'सेवामूलक(Service)'), ('O', 'अन्य(Others)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='investment',
            field=models.CharField(blank=True, choices=[('MINIATURE', 'लघु (Micro)'), ('DOMESTIC', 'घरेलु (Cottage Industry)'), ('SMALL', 'साना (Small)'), ('MEDIUM', 'मझौला (Medium)'), ('LARGE', 'ठुलो (Large)')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='local_body',
            field=models.CharField(blank=True, choices=[('AMARGADHI', 'अमरगढी नगरपालिका'), ('PARSURAM', 'परशुराम नगरपालिका'), ('ALITAL', 'आलिताल गाउँपालिका'), ('BHAGYASWOR', 'भागेश्वर गाउँपालिका'), ('NAVADURGA', 'नवदुर्गा गाउँपालिका'), ('AJAYMERU', 'अजयमेरु गाउँपालिका'), ('GANYAPDHURA', 'गन्यापधुरा गाउँपालिका'), ('MAHAKALI', 'महाकाली नगरपालिका'), ('SALYASIKHAR', 'शैल्यशिखर नगरपालिका'), ('MALIKARJUN', 'मालिकार्जुन गाउँपालिका'), ('APIHIMAL', 'अपिहिमाल गाउँपालिका'), ('DUNHU', 'दुहुँ गाउँपालिका'), ('NAUGADH', 'नौगाड गाउँपालिका'), ('MARMA', 'मार्मा गाउँपालिका'), ('LEKAM', 'लेकम गाउँपालिका'), ('BYAS', 'ब्याँस गाउँपालिका'), ('DASHRATHCHAND', 'दशरथचन्द नगरपालिका'), ('PATAN', 'पाटन नगरपालिका'), ('MELAULI', 'मेलौली नगरपालिका'), ('PURCHAUDI', 'पुर्चौडी नगरपालिका'), ('SUNARYA', 'सुर्नया गाउँपालिका'), ('SIGAS', 'सिगास गाउँपालिका'), ('SHIVNATH', 'शिवनाथ गाउँपालिका'), ('PARBESHWOR', 'पञ्चेश्वर गाउँपालिका'), ('DOGDAKEDAR', 'दोगडाकेदार गाउँपालिका'), ('DILASAINI', 'डीलासैनी गाउँपालिका'), ('MANGALSENA', 'मंगलसेन नगरपालिका'), ('KAMALBAJAR', 'कमलबजार नगरपालिका'), ('SANFEBAGAR', 'साँफेबगर नगरपालिका'), ('PANCHADEBAL', 'पन्चदेवल विनायक नगरपालिका'), ('CHAURPATI', 'चौरपाटी गाउँपालिका'), ('MELLEKH', 'मेल्लेख गाउँपालिका'), ('BATRIGADHI', 'बान्निगढी जयगढ गाउँपालिका'), ('RAMAROSAN', 'रामारोशन गाउँपालिका'), ('DHAKARI', 'ढकारी गाउँपालिका'), ('TURMAKHAND', 'तुर्माखाँद गाउँपालिका'), ('DIPAYAL', 'दिपायल सिलगढी नगरपालिका'), ('SHIKHAR', 'शिखर नगरपालिका'), ('PURBICHAUKI', 'पूर्वीचौकी गाउँपालिका'), ('BADIKEDAR', 'बडीकेदार गाउँपालिका'), ('JORAYAL', 'जोरायल गाउँपालिका'), ('SAYAL', 'सायल गाउँपालिका'), ('AADARSH', 'आदर्श गाउँपालिका'), ('KIC', 'के.आई.सिं. गाउँपालिका'), ('BOGTAN', 'बोगटान फुड्सिल गाउँपालिका'), ('DHANGADI', 'धनगढी उपमहानगरपालिका'), ('TIKAPUR', 'टिकापुर नगरपालिका'), ('GHODAGHODI', 'घोडाघोडी नगरपालिका'), ('LAMKICHUHA', 'लम्कीचुहा नगरपालिका'), ('VAJANI', 'भजनी नगरपालिका'), ('GODAWARI', 'गोदावरी नगरपालिका'), ('GAURIGANGA', 'गौरीगंगा नगरपालिका'), ('JANAKI', 'जानकी गाउँपालिका'), ('BARDAGORIYA', 'बर्दगोरिया गाउँपालिका'), ('MOHANYAL', 'मोहन्याल गाउँपालिका'), ('KAULARI', 'कैलारी गाउँपालिका'), ('JOSHIPUR', 'जोशीपुर गाउँपालिका'), ('CHURE', 'चुरे गाउँपालिका'), ('BADIMALIKA', 'बडीमालिका नगरपालिका'), ('TRIBENI', 'त्रिवेणी नगरपालिका'), ('BUDHIGANGA', 'बुढीगंगा नगरपालिका'), ('BUDHINANDA', 'बुढीनन्दा नगरपालिका'), ('GAUMUL', 'गौमुल गाउँपालिका'), ('JAGANNATH', 'जगन्\u200dनाथ गाउँपालिका'), ('SWAMIKARTIK', 'स्वामीकार्तिक खापर गाउँपालिका'), ('KHAPTAD', 'खप्तड छेडेदह गाउँपालिका'), ('HIMALI', 'हिमाली गाउँपालिका'), ('BHIMDATTA', 'भीमदत्त नगरपालिका'), ('PURNABAS', 'पुर्नवास नगरपालिका'), ('BEDKOT', 'वेदकोट नगरपालिका'), ('DODHARA', 'दोधारा चादँनी नगरपालिका'), ('SUKLAPHATA', 'शुक्लाफाँटा नगरपालिका'), ('BELAURI', 'बेलौरी नगरपालिका'), ('KRISHNAPUR', 'कृष्णपुर नगरपालिका'), ('BELDADI', 'बेलडाडी गाउँपालिका'), ('LALJHADI', 'लालझाडी गाउँपालिका'), ('JAYPRITHVI', 'जयपृथ्वी नगरपालिका'), ('BUNGAL', 'बुंगल नगरपालिका'), ('TALKOT', 'तलकोट गाउँपालिका'), ('MASTA', 'मष्टा गाउँपालिका'), ('KHAPTADCHATRA', 'खप्तडछान्ना गाउँपालिका'), ('THALARA', 'थलारा गाउँपालिका'), ('BITTADCHIR', 'वित्थडचिर गाउँपालिका'), ('SURMA', 'सूर्मा गाउँपालिका'), ('CHABBISPATHIVERA', 'छबिसपाथिभेरा गाउँपालिका'), ('DURGATHALI', 'दुर्गाथली गाउँपालिका'), ('KEDARSU', 'केदारस्युँ गाउँपालिका'), ('SAIPAL', 'साइपाल गाउँपालिका')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='machinery_tool',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='ownership',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'निजी (Private)'), ('PARTNERSHIP', 'साझेदारी (Partnership)')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='product_description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='product_service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='raw_material_source',
            field=models.CharField(blank=True, choices=[('LOCAL', 'स्थानिय (Local)'), ('IMPORTED', 'आयातित (Imported)')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='settlement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'पुरुष (Male)'), ('FEMALE', 'महिला (Female)'), ('OTHERS', 'अन्य (Others)')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='skillfull',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='unskilled',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='industrywithoutgis',
            name='ward_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
