# Generated by Django 4.1 on 2023-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_without_gis', '0002_rename_industry_address_industrywithoutgis_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrywithoutgis',
            name='others_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
