# Generated by Django 4.1 on 2023-09-18 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('industry_without_gis', '0003_industrywithoutgis_others_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrywithoutgis',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
