deployment:
  tasks:
    - export DEPLOYPATH=/home/kantggjb/industry/ #this is original
    - /bin/cp -r accounts $DEPLOYPATH
    - /bin/cp -r faq $DEPLOYPATH
    - /bin/cp -r fonts $DEPLOYPATH
    - /bin/cp -r industry $DEPLOYPATH
    - /bin/cp -r industry_without_gis $DEPLOYPATH
    - /bin/cp -r report $DEPLOYPATH
    - /bin/cp -r static $DEPLOYPATH
    - /bin/cp -r templates $DEPLOYPATH