# Generated by Django 4.1 on 2023-04-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=255)),
                ('industry_type', models.CharField(max_length=255)),
                ('industry_category', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('contact_person', models.CharField(max_length=255)),
                ('industry_capital', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('established_date', models.DateField()),
                ('nature_of_investment', models.CharField(choices=[('L', 'LAGHU UDHAM'), ('G', 'GHARELU'), ('S', 'SMALL'), ('M', 'MEDIUM'), ('B', 'BIG')], max_length=1)),
                ('raw_material_source', models.CharField(choices=[('L', 'LOCAL'), ('O', 'OUT')], max_length=1)),
                ('current_status', models.CharField(choices=[('A', 'Active'), ('S', 'Semi Active'), ('I', 'Inactive')], max_length=1)),
                ('type_of_product_based_on_industry', models.CharField(choices=[('E', 'Energy Industry'), ('MA', 'Manufacturing Industry'), ('AGFO', 'Agriculture and Forestry Industry'), ('MI', 'Mineral Industry'), ('I', 'Infrastructure Industry'), ('T', 'Tourism Industry'), ('ITCT', 'Information Technology & Communication Technology Industry'), ('S', 'Service Industry')], max_length=4)),
                ('renew_expire_date', models.DateField()),
                ('name_of_machine_tool', models.CharField(max_length=255)),
                ('capacity_of_industry_operation', models.CharField(choices=[('A', '70-100 %'), ('B', '50-70 %'), ('C', 'Less than 50%'), ('D', 'Less than 25%')], max_length=1)),
                ('brand', models.CharField(max_length=255)),
                ('district', models.CharField(choices=[('KAILALI', 'KAILALI'), ('KANCHANPUR', 'KANCHANPUR'), ('DADELDHURA', 'DADELDHURA'), ('DOTI', 'DOTI'), ('ACHHAM', 'ACHHAM'), ('BAJURA', 'BAJURA'), ('BAJHANG', 'BAJHANG'), ('BAITADI', 'BAITADI'), ('DARCHULA', 'DARCHULA')], max_length=10)),
                ('local_government', models.CharField(max_length=255)),
                ('ward_no', models.CharField(max_length=255)),
                ('tole', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('remarks', models.TextField()),
                ('technical_local', models.CharField(max_length=255)),
                ('technical_outside', models.CharField(max_length=255)),
                ('ad_local', models.CharField(max_length=255)),
                ('ad_outside', models.CharField(max_length=255)),
                ('self_fixed', models.IntegerField()),
                ('self_current', models.IntegerField()),
                ('bank_fixed', models.IntegerField()),
                ('bank_current', models.IntegerField()),
                ('key_challanges', models.CharField(choices=[('I', 'Investment'), ('T', 'Technical Knowledge'), ('M', 'Market'), ('MG', 'Management')], max_length=2)),
                ('expectations_with_gov', models.CharField(choices=[('G', 'Grant'), ('T', 'Training'), ('M', 'Marketing'), ('O', 'Others')], max_length=1)),
                ('industry_photo', models.ImageField(upload_to='image')),
            ],
        ),
    ]
