# Generated by Django 4.1 on 2023-04-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_alter_industry_ad_local_alter_industry_ad_outside_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='ad_local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ad_outside',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='bank_current',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='bank_fixed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_photo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='self_current',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='self_fixed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='technical_local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='technical_outside',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
