# Generated by Django 4.1 on 2023-04-25 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0005_alter_industry_industry_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='year',
        ),
        migrations.AddField(
            model_name='industry',
            name='tax_status',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('remarks', models.TextField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.industry')),
            ],
        ),
    ]
