# Generated by Django 4.1 on 2023-04-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0006_remove_industry_remarks_remove_industry_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='industry.industry'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
