# Generated by Django 4.1 on 2023-04-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0007_alter_product_industry_alter_product_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=444.44, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default='333.3', max_digits=9),
            preserve_default=False,
        ),
    ]
