# Generated by Django 4.1 on 2023-04-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0008_industry_latitude_industry_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='ad_local',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ad_outside',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='technical_local',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='technical_outside',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=255, null=True),
        ),
    ]
