# Generated by Django 4.1 on 2023-04-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0009_alter_industry_ad_local_alter_industry_ad_outside_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.CharField(blank=True, choices=[('A', '2050'), ('B', '2051'), ('C', '2052')], default='A', max_length=5, null=True),
        ),
    ]
