# Generated by Django 4.1 on 2023-04-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0011_rename_capacity_of_industry_operation_industry_current_running_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='district',
            field=models.CharField(max_length=100),
        ),
    ]
