# Generated by Django 4.1 on 2023-04-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0014_alter_industry_latitude_alter_industry_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
