# Generated by Django 4.1 on 2023-05-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0015_alter_industry_latitude_alter_industry_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
