# Generated by Django 4.1 on 2023-05-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0016_alter_industry_industry_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='industry_photo',
        ),
        migrations.CreateModel(
            name='IndustryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.industry')),
            ],
        ),
    ]
