# Generated by Django 4.1 on 2023-05-10 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0017_remove_industry_industry_photo_industryphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryphoto',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_photo', to='industry.industry'),
        ),
        migrations.AlterField(
            model_name='industryphoto',
            name='photo',
            field=models.ImageField(default='ss', upload_to='images'),
            preserve_default=False,
        ),
    ]
