# Generated by Django 4.1 on 2023-05-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0018_alter_industryphoto_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='current_capital',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='industry',
            name='female',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='industry',
            name='fixed_capital',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='industry',
            name='foreign',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='industry',
            name='indigenous',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='industry',
            name='male',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='industry',
            name='skillfull',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='industry',
            name='total_capital',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='industry',
            name='total_manpower',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='industry',
            name='unskilled',
            field=models.IntegerField(),
        ),
    ]
