# Generated by Django 4.1 on 2023-05-14 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0020_alter_industry_address_alter_industry_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='address',
            field=models.CharField(blank=True, default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='contact_person',
            field=models.CharField(blank=True, default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='current_capital',
            field=models.CharField(blank=True, default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='district',
            field=models.CharField(blank=True, default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='female',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='fixed_capital',
            field=models.CharField(blank=True, default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='foreign',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='indigenous',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_reg_no',
            field=models.CharField(blank=True, default=3, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='latitude',
            field=models.CharField(blank=True, default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='local_body',
            field=models.CharField(blank=True, default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='longitude',
            field=models.CharField(blank=True, default=22, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='machinery_tool',
            field=models.TextField(blank=True, default='ww', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='male',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='mobile_number',
            field=models.CharField(blank=True, default=44444444444, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='owner_name',
            field=models.CharField(blank=True, default='ss', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='product_description',
            field=models.TextField(blank=True, default='aa', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='product_service_name',
            field=models.CharField(blank=True, default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='reg_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='settlement',
            field=models.CharField(blank=True, default='ss', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='skillfull',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='telephone_number',
            field=models.CharField(blank=True, default=33444444444, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='total_capital',
            field=models.CharField(blank=True, default=44, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='total_manpower',
            field=models.IntegerField(blank=True, default=33),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='unskilled',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='ward_no',
            field=models.CharField(blank=True, default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='yearly_capacity',
            field=models.CharField(blank=True, default='s', max_length=100),
            preserve_default=False,
        ),
    ]
