# Generated by Django 4.1 on 2023-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0021_alter_industry_address_alter_industry_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry_reg_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
