# Generated by Django 4.1 on 2023-05-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0022_alter_industry_industry_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry_reg_no',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
