# Generated by Django 4.1 on 2023-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0023_alter_industry_industry_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='current_capital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='fixed_capital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='foreign',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='indigenous',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_reg_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='local_body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='machinery_tool',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='owner_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='industry',
            name='product_description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='product_service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='reg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='settlement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='skillfull',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='total_capital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='total_manpower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='unskilled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ward_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='yearly_capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
