# Generated by Django 4.1 on 2023-05-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0024_alter_industry_address_alter_industry_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='caste',
            field=models.CharField(blank=True, choices=[('DALIT', 'दलित (Dalit)'), ('JANAJATI', 'जनजाती (Janajati)'), ('OTHERS', 'अन्य (Others)')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='current_running_capacity',
            field=models.CharField(blank=True, choices=[('A', '७०-१००% (70-100%)'), ('B', '५०-७०% (50-70%)'), ('C', '५०% भन्दा कम (Less than 50%)'), ('D', '२५% भन्दा कम (Less than 25%)')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='current_status',
            field=models.CharField(blank=True, choices=[('A', 'चालु(Active)'), ('I', 'निष्कृय(Inactive)')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_acc_product',
            field=models.CharField(blank=True, choices=[('E', 'उर्जामूलक (Energy)'), ('MF', 'उत्पादनमूलक (Manufacturing)'), ('AF', 'कृषि तथा वन पैदावारमा आधारित (Agricultural or Forestry based)'), ('MI', 'खनिज(Mineral)'), ('I', 'पूर्वाधार(Infrastructure)'), ('T', 'पर्यटन(Tourism)'), ('IC', 'सूचना तथा संचार प्रविधि(Information and Communication)'), ('S', 'सेवामूलक(Service)'), ('O', 'अन्य(Others)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='investment',
            field=models.CharField(blank=True, choices=[('MINIATURE', 'लघु (Miniature)'), ('DOMESTIC', 'घरेलु (Domestic)'), ('SMALL', 'साना (Small)'), ('MEDIUM', 'मझौला (Medium)'), ('LARGE', 'ठुलो (Large)')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ownership',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'निजी (Private)'), ('PARTNERSHIP', 'साझेदारी (Partnership)')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='raw_material_source',
            field=models.CharField(blank=True, choices=[('LOCAL', 'स्थानिय (Local)'), ('IMPORTED', 'आयातित (Imported)')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'पुरुष (Male)'), ('FEMALE', 'महिला (Female)'), ('OTHERS', 'अन्य (Others)')], max_length=6, null=True),
        ),
    ]
