# Generated by Django 4.1 on 2023-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0025_alter_industry_caste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry_reg_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
