# Generated by Django 4.1 on 2023-05-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0026_alter_industry_industry_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='female',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='foreign',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='indigenous',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='male',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='skillfull',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='total_manpower',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='unskilled',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
