# Generated by Django 4.1 on 2023-05-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0027_alter_industry_female_alter_industry_foreign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='others_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
