# Generated by Django 4.1 on 2023-05-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0028_industry_others_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='female',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='foreign',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='indigenous',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='male',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='skillfull',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='total_manpower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='unskilled',
            field=models.IntegerField(default=0),
        ),
    ]
