# Generated by Django 4.1 on 2023-05-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0029_alter_industry_female_alter_industry_foreign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='female',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='foreign',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='indigenous',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='male',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='skillfull',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='total_manpower',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='industry',
            name='unskilled',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
