# Generated by Django 4.1 on 2023-05-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0031_alter_industry_female_alter_industry_foreign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='current_capital',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='fixed_capital',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='total_capital',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
