# Generated by Django 4.1 on 2023-05-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0032_alter_industry_current_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='yearly_capacity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
