# Generated by Django 4.1 on 2023-07-27 11:01

from django.db import migrations, models
import industry.validators


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0033_alter_industry_yearly_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='investment',
            field=models.CharField(blank=True, choices=[('MINIATURE', 'लघु (Miniature)'), ('DOMESTIC', 'घरेलु (Cottage Industry)'), ('SMALL', 'साना (Small)'), ('MEDIUM', 'मझौला (Medium)'), ('LARGE', 'ठुलो (Large)')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='reg_date',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[industry.validators.nepali_date_validator]),
        ),
    ]
