# Generated by Django 4.1 on 2023-08-15 08:20

from django.db import migrations, models
import industry.validators


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0037_alter_industry_investment_alter_industry_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='reg_date',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[industry.validators.nepali_date_validator]),
        ),
    ]
