# Generated by Django 4.1 on 2023-09-18 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0038_alter_industry_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
